### PR TITLE
Fixing "MeshModifiers" error in input files of problems/snow_2d/

### PR DESCRIPTION
**Pull request by vishankkumar**
Dear Developer,

I was testing some examples and there was an error of "[MeshModifiers]", which were blank so I have removed it. Perhaps its a deprecated class or something still under development. Anyhow, as the block was empty there should not be any impact on the result. So would you please accept the pull request to make these changes in the default branch.

### CODE REVIEW

**Comment by aeslaughter** [comment]
Thanks! It was removed.

**Comment by aeslaughter** [comment]
What is your interest in Pika?

**Comment by vishankkumar** [comment]
I am trying to perform some phase field simulations for battery
applications, where I will couple them with electrochemical equations. So,
I was wondering if I should build from Pika or from phase-field module of
MOOSE.

Thanks,
Vishank

**Comment by aeslaughter** [comment]
phase-field module, Pika is fairly old and doesn't utilize the full capability in the module

**Comment by vishankkumar** [comment]
Aaah okay, thanks Andrew. Then I will develop on Phase field module itself.

If I may ask a small question regarding the kernels? I followed your MOOSE
workshop and learned a lot from it and to be put in one line, you have to
write your kernel for each of the term and the kernels add up on default
and in the .C file you have to define the precomputeQPResidual or
computeQPResidual depending on the case. My question is, do you still need
to worry about off diagonal terms and Jacobian terms?

Kind regards,
Vishank

**Comment by aeslaughter** [comment]
No, the tutorial uses automatic differentiation to compute those via the ADKernel class.

**Pull request merged**
